apiVersion: v2
name: jellyfin
description: A Helm chart for Jellyfin Media Server
type: application
home: https://jellyfin.org/
icon: https://jellyfin.org/images/logo.svg
keywords:
  - jellyfin
  - media
  - self-hosted
version: 3.1.0
appVersion: 10.11.5
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Add options for customizing the ingress service
