# markdownlint configuration
# https://github.com/DavidAnson/markdownlint

default: true

# MD013/line-length - Line length
MD013:
  line_length: 120
  tables: false
  code_blocks: false

# MD033/no-inline-html
MD033: false

# MD041/first-line-heading
MD041: false
