name: Docs Update

on:
  push:
    branches:
      - master

permissions:
  contents: write
  packages: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        fetch-depth: 0

    - name: Helm Docs GitHub Action
      uses: losisin/helm-docs-github-action@6bf14d5bdb7346c5876b2b3ea96bfb8f0f53c556 # v1.3.4
      with:
        git-push: true
        git-commit-message: "docs(charts): :memo: write updated reademe"

    - name: Push changes
      run: git push