name: Docs Update

on:
  push:
    branches:
      - master

permissions:
  contents: write
  packages: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      with:
        fetch-depth: 0

    - name: Helm Docs GitHub Action
      uses: losisin/helm-docs-github-action@2ccf3e77eb70dc80d62f8cc26f15d0a96b75fef4 # v1.8.0
      with:
        git-push: true
        git-commit-message: "docs(charts): :memo: write updated reademe"

    - name: Push changes
      run: git push