name: Pull Request

on:
  - pull_request

permissions:
  contents: write
  packages: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Helm Docs GitHub Action
      uses: losisin/helm-docs-github-action@v1.3.1
      with:
        git-push: true
        git-commit-message: "docs(charts): :memo: write updated reademe"